language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAJVEQVENBCEUHCJ5A
  secret_access_key: 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
  bucket: www.vsrivastava.com
  region: us-west-1
